# Site settings
title: rocvoc
heading: Kevin O'Connor.
tagline: Hopefully someone is interested in all of this.
avatar: /assets/images/ko-profile-1.jpeg

url: "https://kevin.rocvoc.com"
baseurl: ""

permalink: /:year/:month/:day/:title/
markdown: kramdown

# Don't publish these to the site
exclude:
  - README.md
  - reference/
