# Site settings
title: rocvoc
heading: Kevin O'Connor.
tagline: Hopefully someone is interested in all of this.
avatar: /assets/images/ko-profile-1.jpeg

# URL settings — when you move to a custom domain, set url to the domain
# and change baseurl to "" (empty).
url: "https://top-shelf-steve.github.io"
baseurl: "/tss-blog"

permalink: /:year/:month/:day/:title/
markdown: kramdown

# Don't publish these to the site
exclude:
  - README.md
  - reference/
